import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from './components/Providers';
import AddNewTaskModal from './components/AddNewTaskModal';
import GlobalWrapper from './components/GlobalWrapper/GlobalWrapper';
import { CssBaseline } from '@mui/joy';
import ScrollToTopButton from './components/ScrollToTopButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'To-do App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CssBaseline />
        <Providers>
          <ScrollToTopButton />
          <AddNewTaskModal />
          <GlobalWrapper> {children}</GlobalWrapper>
        </Providers>
      </body>
    </html>
  );
}
